Add API functions
qerdcv/p-bot pull request #17
Opened 2022-07-13 19:02 UTC by Eiphoria

2022-07-13 19:35 UTC, Drozd0f requested changes

2022-07-13 19:35 UTC, Drozd0f commented on pidorbot/src/db.py
> +    def to_dict(self):
Add type hint for this method (what that return)

2022-07-13 19:35 UTC, Drozd0f commented on pidorbot/src/db.py
> +    def to_dict(self):
Similarly need type hint

2022-07-13 19:35 UTC, Drozd0f commented on pidorbot/src/db.py
>  def result_to_stat(result, chat_id):
You can use `Optional` to type hint what this function will return

2022-07-13 19:35 UTC, Drozd0f commented on pidorbot/src/db.py
> +    return None
The function always returns `None`. I think it's no need

2022-07-14 06:48 UTC, qerdcv commented
https://user-images.githubusercontent.com/52095526/178919040-6141d1b1-e840-4a2e-8cb5-91238cfb8048.mp4

2022-07-14 12:33 UTC, merged